machine:
  name: BAVV_BO_MCH
  bank: BAVV
  app: BO
  nodemanager:
    listen_address: "{{ ansible_host }}"
  server: 
    name: BAVV_BO_SERVER
    port: 8001
    listen_address: "{{ ansible_host }}"
  filestore:
    name_prefix: "FS_"
    path: "/u01/Admin/filestore"
  jms_server:
    name_prefix: "JMS_"
    name_sufix: "JMSModule"
  # saf_agent:
  #   name_prefix: "SAF_"
