---
# - name: Descargando Java
#   get_url:
#     url: http://10.0.0.14:7000/downloads/java/{{ java_version }}
#     dest: /root/{{ java_version }}

- name: Descargando el instalador de Java
  copy:
    src: /home/osboxes/Descargas/ansible/{{ java_version }}
    dest: /root/{{ java_version }}
    owner: "{{ weblogic.system.user.name }}"
    group: "{{ weblogic.system.user.group }}"
    mode: 0754

- name: Instalando Java
  yum:
    name: /root/{{ java_version }}
    state: present