---
- name: Actualizando paquetes del sistema
  yum:
    name: "*"
    state: present

- name: Agregando epel-release a repositorios
  yum:
    name: epel-release
    state: present

- name: Instalando paquetes base del sistema
  yum:
    name:
      - htop
      - rsync
      - git
      - curl
      - jq
      - nfs-utils
      - nano
      - telnet
      - unzip
    state: present

- name: Zona horaria Santiago
  timezone:
    name: America/Santiago

- name: Creando grupo
  group:
    name: "{{ weblogic.system.user.group }}"

- name: Creando usuario y agregandolo al grupo creado
  user:
    name: "{{ weblogic.system.user.name }}"
    group: "{{ weblogic.system.user.group }}"
    password: $6$mysecretsalt$lxylT5/9wlw9WuBfvTqwo3NjO1PJwZTV4KVGSAIe2xlTgChgaK.4sJh2y2OtiDFettZkCfZcdvLXfeutyXaxA.

- name: Check if java is installed
  command: java -version
  register: java_result
  ignore_errors: True
  changed_when: False

- name: Instalando Java
  # Invocar playbook java8.yml 
  import_tasks: java8.yml
  when: java_result is failed

- name: Crear directorio u01
  file:
    path: /u01
    state: directory
    owner: "{{ weblogic.system.user.name }}"
    group: "{{ weblogic.system.user.group }}"
    mode: '0755'

- name: Crear directorio para properties icbs
  file:
    path: /icbs/config
    owner: "{{ weblogic.system.user.name }}"
    group: "{{ weblogic.system.user.group }}"
    state: directory
    recurse: yes
    mode: '0755'
  when:
    - inventory_hostname != "adminserver"

- name: Crea directorio properties para NFS
  file:
    path: "/icbs/{{ item }}/config"
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall
  loop:
    - BBTA
  when:
    - inventory_hostname == "adminserver"

- name: Crea directorios icbs
  file:
    path: "/icbs/data/{{ item }}"
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall
  loop:
    - email
    - entrada
    - entradaDomiciliacion
    - entradaMatricula
    - entradaMasiva
    - entradaSolicitud
    - entraditaSolicitud
    - enviados_copia
    - fm-sync-copy
    - migracion
    - reportesSolucion
    - salida
    - salidaDomiciliacion
    - salidaFacturacion
    - salidaMatricula
    - salidaMigracionPSP
    - statistical-reports
    - temp

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Crear directorio para llave ssh
  file:
    path: /home/{{ weblogic.system.user.name }}/.ssh
    owner: "{{ weblogic.system.user.name }}"
    group: "{{ weblogic.system.user.group }}"
    state: directory
    mode: '0755'

- name: Copiar llaves autorizadas a usuario {{ weblogic.system.user.name }}
  copy:
    src: /root/.ssh/authorized_keys
    dest: /home/{{ weblogic.system.user.name }}/.ssh/authorized_keys
    owner: "{{ weblogic.system.user.name }}"
    group: "{{ weblogic.system.user.group }}"
    mode: '0644'
    remote_src: yes

- name: Creando servicio nodemanager
  template:
    src: nodemanager.service.j2
    dest: /etc/systemd/system/nodemanager.service
    mode: '0644'
  when:
    - inventory_hostname != "adminserver"

- name: Reload daemon configs
  systemd:
    name: nodemanager
    enabled: yes
    daemon_reload: yes
  when:
    - inventory_hostname != "adminserver"